# Generated by Django 4.2.14 on 2024-07-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория товаров')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price', models.IntegerField(verbose_name='Стоимость товара')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии ли товар')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления объявления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
